language: python
matrix:
  include:
  - os: linux
    dist: trusty
    python: '2.6'
  - os: linux
    dist: trusty
    python: '2.7'
  - os: linux
    dist: trusty
    python: '3.3'
  - os: linux
    dist: trusty
    python: '3.4'
  - os: linux
    dist: trusty
    python: '3.5'
# command to install dependencies
# install: "pip install -r requirements.txt"
# # command to run tests
script: python -m unittest discover
